language: node_js
services:
- couchdb
node_js:
- 9
- 8
- 6
before_script:
- "curl -X DELETE http://localhost:5984/bicycle"
after_success:
- npx nyc npm test
- npx nyc report --reporter=text-lcov | npx coveralls
