sudo: false
language: node_js
notifications:
  email: false
services:
- couchdb
node_js:
- stable
- 10
- 8
before_script:
- "curl -X DELETE http://localhost:5984/bicycle"
- npm i -g npm
- npm prune
after_success:
- npx nyc npm test
- npx nyc report --reporter=text-lcov | npx coveralls
